// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/usr/lib/petscdir/petsc3.19/x86_64-linux-gnu-rea
//                                  l/include', '/usr/lib/slepcdir/slepc3.19/x86_64-li
//                                  nux-gnu-real/include', '/usr/lib/x86_64-linux-gnu/
//                                  openmpi/include/openmpi', '/usr/lib/x86_64-linux-g
//                                  nu/openmpi/include', '/usr/include/hdf5/openmpi', 
//                                  '/usr/include/eigen3', '/usr/lib/python3/dist-pack
//                                  ages/ffc/backends/ufc']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#ifndef __FFC_COORDINATE_MAPPING_A6CFCB374A046B310D251AE608A15B73255FD911_H
#define __FFC_COORDINATE_MAPPING_A6CFCB374A046B310D251AE608A15B73255FD911_H
#include "ffc_element_8aa3ceb94d6214f7f1b8870d7aba5c611a9b0f66.h"
#include "ffc_element_948cd5e3217da7acb00d781d631a62ce17079ff5.h"
#include <algorithm>
#include <iostream>
#include <stdexcept>
#include <ufc.h>

class ffc_coordinate_mapping_a6cfcb374a046b310d251ae608a15b73255fd911_coordinate_mapping_main: public ufc::coordinate_mapping
{
public:

  ffc_coordinate_mapping_a6cfcb374a046b310d251ae608a15b73255fd911_coordinate_mapping_main();

  ~ffc_coordinate_mapping_a6cfcb374a046b310d251ae608a15b73255fd911_coordinate_mapping_main() override;

  const char * signature() const final override;

  ufc::coordinate_mapping * create() const final override;

  std::size_t geometric_dimension() const final override;

  std::size_t topological_dimension() const final override;

  ufc::shape cell_shape() const final override;

  ufc::finite_element * create_coordinate_finite_element() const final override;

  ufc::dofmap * create_coordinate_dofmap() const final override;

  void compute_physical_coordinates(
      double * x, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs) const final override;

  void compute_reference_coordinates(
      double * X, std::size_t num_points,
      const double * x,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_reference_geometry(
      double * X, double * J, double * detJ, double * K, std::size_t num_points,
      const double * x,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_jacobians(
      double * J, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs) const final override;

  void compute_jacobian_determinants(
      double * detJ, std::size_t num_points,
      const double * J,
      int cell_orientation) const final override;

  void compute_jacobian_inverses(
      double * K, std::size_t num_points,
      const double * J, const double * detJ) const final override;

  void compute_geometry(
      double * x, double * J, double * detJ, double * K, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_midpoint_geometry(
      double * x, double * J,
      const double * coordinate_dofs) const final override;

};

extern "C" ufc::coordinate_mapping * create_ffc_coordinate_mapping_a6cfcb374a046b310d251ae608a15b73255fd911_coordinate_mapping_main();

#endif
